### ISSUE TITLE
Checklist before first Alpha release.

### ISSUE THREAD

**Issue by Yusarina** [teamneoneko/Avatar-Toolkit#70]
### Overhaul
- [x] All bugs fixes, all features working, see https://github.com/teamneoneko/Avatar-Toolkit/pull/81

### Importers:
- [x] VRM Importer
- [x] FBX Importer 

### Optimization Tools 

- [x] Remove Doubles 
- [x] Join meshes
- [x] Combine Materials 

### Additional Tools

- [x] Separate by materials and loose parts
- [x] Apply Transforms
- [x] Remove unused shapekeys 
- [x] Remove Zero weight bones
- [x] Connect Bones
- [x] Delete Bone Constraints 

### Merge Armatures

- [x] Merge Armature system which works.

### Visemes Creation

- [x] Visemse creation system which works.

### Settings:

- [x] Plugin Language
- [x] Updater

### About section

- [x] Credit Section
- [x] Where to support us
- [x] Discord and Wiki link.

### Anything else which is in the plugin and is stable enough to push to the public is just a bonus, anything unstable should be put into the dev branch unto it's more stable to push.

**Comment by Yusarina** [comment]
Everything but the MMD Importer has been done @989onan now, so once we (Hopefully) manage to get the MMD Importer done, it's just improvements and fixes unto the first release.

**Comment by Yusarina** [comment]
Plan is once this has been merged: https://github.com/teamneoneko/Avatar-Toolkit/pull/81, hopefully "figures cross" the first Alpha can be release, however it won't be merged unto I gotten everything that needs doing done.
